import { useMutation, useQuery } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, Text, View } from "react-native";
import { Button, ErrorState, Screen, TextField } from "@/src/components/ui";
import { auditKeys, createAudit, getCountries, getLocations } from "@/src/features/audits/api";
import { useAuth } from "@/src/features/auth/session";
import { queryClient } from "@/src/api/query-client";
import { useForm } from "react-hook-form";
export default function CreateAudit() { const { user } = useAuth(); const fields=useForm<{name:string;workArea:string}>({defaultValues:{name:"",workArea:""}}); const name=fields.watch("name"),workArea=fields.watch("workArea"); const [country,setCountry]=useState<string|number>(""); const [location,setLocation]=useState<string|number>(""); const lookups=useQuery({ queryKey:["audit-lookups"], queryFn:async()=>({countries:await getCountries(),locations:await getLocations()})}); const mutation=useMutation({mutationFn:createAudit,onSuccess:async(a)=>{await queryClient.invalidateQueries({queryKey:auditKeys.all});router.replace({pathname:"/(app)/audits/[auditId]",params:{auditId:String(a.id)}})}}); if(lookups.error)return <Screen><ErrorState message={lookups.error.message} retry={()=>void lookups.refetch()}/></Screen>; const valid=name.trim()&&country!==""&&location!==""; return <Screen><TextField label="Audit name *" value={name} onChangeText={(value)=>fields.setValue("name",value)}/><Text className="mb-2 font-semibold text-ink">Country *</Text><View className="mb-4 flex-row flex-wrap gap-2">{lookups.data?.countries.map(x=><Pressable key={String(x.id)} onPress={()=>setCountry(x.id)} className={`min-h-11 justify-center rounded-xl border px-3 ${country===x.id?"border-brand bg-red-50":"border-slate-300 bg-white"}`}><Text>{x.country_name??x.name??String(x.id)}</Text></Pressable>)}</View><Text className="mb-2 font-semibold text-ink">Location *</Text><View className="mb-4 flex-row flex-wrap gap-2">{lookups.data?.locations.map(x=><Pressable key={String(x.id)} onPress={()=>setLocation(x.id)} className={`min-h-11 justify-center rounded-xl border px-3 ${location===x.id?"border-brand bg-red-50":"border-slate-300 bg-white"}`}><Text>{x.location_name??x.name??String(x.id)}</Text></Pressable>)}</View><TextField label="Work area" value={workArea} onChangeText={(value)=>fields.setValue("workArea",value)}/>{mutation.error?<Text className="mb-3 text-red-700">{mutation.error.message}</Text>:null}<Button title={mutation.isPending?"Creating…":"Create audit"} disabled={!valid||mutation.isPending} onPress={()=>user&&mutation.mutate({auditor_id:user.id,audit_name:name.trim(),country,location,...(workArea?{work_area:workArea}: {})})}/></Screen>; }
